openapi: 3.0.0
info:
  title: Butler API
  description: Butler API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: 本番環境

paths:
  /api/signup:
    post:
      summary: サインアップ
      description: ユーザーサインアップ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ユーザーネーム
                email:
                  type: string
                  format: email
                  description: メールアドレス
                password:
                  type: string
                  description: パスワード
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: ユーザー登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: ユーザーネーム
                  message:
                    type: string
                    description: メッセージ
                required:
                  - message
    
  /api/signin:
    post:
      summary: サインイン
      description: ユーザーサインイン
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: メールアドレス
                password:
                  type: string
                  description: パスワード
              required:
                - email
                - password
      responses:
        '200':
          description: ユーザー認証成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: ユーザーネーム
                  message:
                    type: string
                    description: メッセージ
                  token:
                    type: string
                    description: JWTトークン
                required:
                  - message

  /api/chats:
    get:
      summary: ユーザーのチャットルーム一覧
      description: ユーザーのチャットルームを全て取得
      responses:
        '200':
          description: チャットルーム取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    description: チャットルーム一覧
                    items:
                      type: object
                      properties:
                        chat_id:
                          type: string
                          description: チャットルームID
    post:
      summary: チャット新規作成
      description: チャット新規作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: private or group
                chatName:
                  type: string
                  description: チャットルーム名
                participants:
                  type: array
                  description: チャット参加者
                  items:
                    type: object
                    properties:
                      uid:
                        type: string
                        description: ユーザーID
              required:
                - type
                - participants
      responses:
        '201':
          description: チャットルーム作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  chatId:
                    type: string
                    description: チャットルームID
                  type:
                    type: string
                    description: private or group
                  chatName:
                    type: string
                    description: チャットルーム名
                  participants:
                    type: array
                    items:
                      type: object
                      properties:
                        uid:
                          type: string
                          description: ユーザーID
                    description: チャット参加者
                  createdAt:
                    type: string
                    format: date-time
                    description: チャットルーム作成日時
                  updatedAt:
                    type: string
                    format: date-time
                    description: チャットルーム更新日時

  /api/messages:
    get:
      summary: チャットルームのメッセージ取得
      description: 指定されたチャットルームのメッセージを取得
      parameters:
        - name: chatId
          in: query
          required: true
          schema:
            type: string
          description: 取得するチャットルームのID
      responses:
        '200':
          description: メッセージ取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    description: メッセージ一覧
                    items:
                      type: object
                      properties:
                        messageId:
                          type: string
                          description: メッセージID
                        chatId:
                          type: string
                          description: チャットルームID
                        senderId:
                          type: string
                          description: 送信者のユーザーID
                        content:
                          type: string
                          description: メッセージ内容
                        timestamp:
                          type: string
                          format: date-time
                          description: メッセージ送信日時
    post:
      summary: メッセージ送信
      description: 指定されたチャットルームにメッセージを送信
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId:
                  type: string
                  description: 送信先のチャットルームID
                senderId:
                  type: string
                  description: 送信者のユーザーID
                content:
                  type: string
                  description: メッセージ内容
              required:
                - chatId
                - senderId
                - content
      responses:
        '201':
          description: メッセージ送信成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: string
                    description: メッセージID
                  chatId:
                    type: string
                    description: チャットルームID
                  senderId:
                    type: string
                    description: 送信者のユーザーID
                  content:
                    type: string
                    description: メッセージ内容
                  timestamp:
                    type: string
                    format: date-time
                    description: メッセージ送信日時
    delete:
      summary: メッセージ取り消し
      description: 指定されたメッセージを削除
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                messageId:
                  type: string
                  description: 取り消すメッセージのID
              required:
                - messageId
      responses:
        '200':
          description: メッセージ取り消し成功
    put:
      summary: メッセージ編集
      description: 指定されたメッセージの内容を編集
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                messageId:
                  type: string
                  description: 編集するメッセージのID
                newContent:
                  type: string
                  description: 更新後のメッセージ内容
              required:
                - messageId
                - newContent
      responses:
        '200':
          description: メッセージ編集成功
